### ISSUE TITLE
dotnet core 2.0 issue

### ISSUE THREAD

**Issue by NicolaasVB** [digipolisantwerp/auth_aspnetcore#3]
This library doesn't seem to play well with dotnet core 2.0.
Somewhat expected though considering the authentication system was overhauled in 2.0 [as shown here](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x)

Below is an image of the exception I get on startup.
![image](https://user-images.githubusercontent.com/2655969/33483870-257846f2-d6a0-11e7-9650-2643b3981d4a.png)

Is there a way to make this library work with dotnet core 1.x? And if so, can you explain how?

Thanks

**Comment by JimmyHannon** [comment]
Prerelease version (3.0.0-beta1) has been published on myget.
